version: "1"
rules:                           # Array of rules
  - base: develop                 # Required. Target branch
    upstream: moment/moment:develop         # Required. Must be in the same fork network.
    autoMerge: false              # Optional, Default: false
    autoMergeHardReset: false     # Optional, Default: false DANGEROUS Wipes target branch changes and reset ref to match upstream
    assignees:
      - mhaamann
      - AbdallaMohamed
    reviewers:
      - mhaamann
      - AbdallaMohamed
label: ":arrow_heading_down: pull"